version: '3.8'

services:
  app:
    image: nextcloud:latest
    restart: always
    ports:
      - 5001:80
    volumes:
      - /mnt/nfstest/test-nextcloud:/var/www/html/data
      - nextcloud:/var/www/html/
      - clamav-sock:/run/clamav
    environment:
      - REDIS_HOST=redis
      - POSTGRES_DB=test-nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud-db-temp-password
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
      - av

  cron:
    image: nextcloud-cron:test
    restart: always
    # user: www-data:www-data
    volumes:
      - /mnt/nfstest/test-nextcloud:/var/www/html/data
      - nextcloud:/var/www/html/
    depends_on: 
      - app
    entrypoint: /cron.sh
  
  av:
    image: clamav/clamav:stable
    volumes:
      - clamav-db:/var/lib/clamav
      - clamav-sock:/tmp

  db:
    image: postgres:13-bookworm
    restart: always
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud-db-temp-password
      - POSTGRES_DB=test-nextcloud
    volumes:
      - postgres:/var/lib/postgresql/data
  
  redis:
    image: redis:bookworm
    restart: always

volumes:
  nextcloud:
  postgres:
  clamav-db:
  clamav-sock:

