version: '3.8'

services:
  app:
    image: nextcloud:${NEXTCLOUD_TAG}
    restart: unless-stopped
    ports:
      - ${NEXTCLOUD_HTTP_PORT}:80
    volumes:
      - ${NEXTCLOUD_DATA_PATH}:/var/www/html/data
      - nextcloud:/var/www/html/
      - clamav-sock:/run/clamav
    environment:
      - REDIS_HOST=redis
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_NEXTCLOUD_USER}
      - POSTGRES_PASSWORD=${POSTGRES_NEXTCLOUD_PASS}
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
      - av

  cron:
    build: 
      context: ./nextcloud-cron
      args:
        - NEXTCLOUD_TAG=${NEXTCLOUD_TAG}
    restart: unless-stopped	
    volumes:
      - ${NEXTCLOUD_DATA_PATH}:/var/www/html/data
      - nextcloud:/var/www/html/
      - clamav-sock:/run/clamav 
    depends_on: 
      - app
    entrypoint: /cron.sh
  
  av:
    image: clamav/clamav:${CLAMAV_TAG}
    volumes:
      - clamav-db:/var/lib/clamav
      - clamav-sock:/tmp

  db:
    image: postgres:${POSTGRESQL_TAG}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_NEXTCLOUD_USER}
      - POSTGRES_PASSWORD=${POSTGRES_NEXTCLOUD_PASS}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
  
  redis:
    image: redis:${REDIS_TAG}
    restart: unless-stopped

volumes:
  nextcloud:
  postgres:
  clamav-db:
  clamav-sock:

